export enum ActionTypes {
  EXAMPLE = 'EXAMPLE',
  AIRLOCK_OPEN = 'AIRLOCK_OPEN',

  PokeGuess = 'POKE_GUESS',

  ScryCurrentDatGameStatus = 'SCRY_CURRENT_DAY_GAME_STATUS',
  ScryUserLedger = 'SCRY_USER_LEDGER',
  ScryLeaderboard = 'SCRY_LEADERBOARD',
  ScryWord = 'SCRY_WORD',

  LOADING_STATE_RESET   = 'LOADING_STATE_RESET',
  INITIAL_SET = 'INITIAL_SET',
  LOADING_SET = 'LOADING_SET',
  SUCCESS_SET = 'SUCCESS_SET',
  ERROR_SET   = 'ERROR_SET',
}
