export enum GetterTypes {
  EXAMPLE_WITH_ARG = 'EXAMPLE_WITH_ARG',

  CurrentGuessCount = 'CURRENT_GUESS_COUNT',
  LetterInGuesses = 'LETTER_IN_GUESSES',
  BestColorForLetterInGuesses = 'BEST_COLOR_FOR_LETTER_IN_GUESSES',

  IsGameFinished = 'IS_GAME_FINISHED',

  LetterMap = 'LETTER_MAP',

  MyScores = 'MY_SCORES',
  MyLedger = 'MY_LEDGER',

  ELEMENT_INITIAL = 'ELEMENT_INITIAL',
  ELEMENT_LOADING = 'ELEMENT_LOADING',
  ELEMENT_SUCCESS = 'ELEMENT_SUCCESS',
  ELEMENT_ERROR = 'ELEMENT_ERROR',
  ELEMENT_STATUS_MAP = 'ELEMENT_STATUS_MAP',
}
